import Head from "next/head";
import styles from "../styles/Home.module.css";

import Banner from "../components/banner/banner";
import NavBar from "../components/nav/navbar";
import SectionCards from "../components/card/section-cards";

import {
  getPopularVideos,
  getVideos,
  getWatchItAgainVideos,
} from "../lib/videos";

export async function getServerSideProps() {
  const userId = "did:ethr:0x24a88B9538286a64B54497246a38bfa732693B80";
  const token =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJkaWQ6ZXRocjoweDI0YTg4Qjk1MzgyODZhNjRCNTQ0OTcyNDZhMzhiZmE3MzI2OTNCODAiLCJwdWJsaWNBZGRyZXNzIjoiMHgyNGE4OEI5NTM4Mjg2YTY0QjU0NDk3MjQ2YTM4YmZhNzMyNjkzQjgwIiwiZW1haWwiOiJhbnNhcmlvdmVzaEB5YWhvby5pbiIsIm9hdXRoUHJvdmlkZXIiOm51bGwsInBob25lTnVtYmVyIjpudWxsLCJpYXQiOjE2NjM1NzE5NTAsImV4cCI6MTY2NDE3Njc1MCwiaHR0cHM6Ly9oYXN1cmEuaW8vand0L2NsYWltcyI6eyJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbInVzZXIiLCJhZG1pbiJdLCJ4LWhhc3VyYS1kZWZhdWx0LXJvbGUiOiJ1c2VyIiwieC1oYXN1cmEtdXNlci1pZCI6ImRpZDpldGhyOjB4MjRhODhCOTUzODI4NmE2NEI1NDQ5NzI0NmEzOGJmYTczMjY5M0I4MCJ9fQ.5DDSWhJEs6pdHDwF1wCAwEUJUiKi0vdTLz6GAU3CzCo";
  const watchItAgainVideos = await getWatchItAgainVideos(userId, token);
  console.log({ watchItAgainVideos });
  const disneyVideos = await getVideos("disney trailer");
  const ProductivityVideos = await getVideos("Shade Zahrai");
  const TravelVideos = await getVideos("World Tour");

  const PopularVideos = await getPopularVideos();

  return {
    props: { disneyVideos, ProductivityVideos, TravelVideos, PopularVideos },
  };
}

export default function Home({
  disneyVideos,
  ProductivityVideos,
  TravelVideos,
  PopularVideos,
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextFlix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <NavBar username="Ovesh@ov.com" />
        <Banner
          videoId="4zH5iYM4wJo"
          title="Clifford the red dog"
          subTitle="a very cute dog"
          imgUrl="/static/clifford.webp"
        />
        <div className={styles.sectionWrapper}>
          <SectionCards title={"Disney"} videos={disneyVideos} size="large" />
          <SectionCards title={"Travel"} videos={TravelVideos} size="small" />
          <SectionCards
            title={"Productivity"}
            videos={ProductivityVideos}
            size="medium"
          />
          <SectionCards title={"Popular"} videos={PopularVideos} size="small" />
        </div>
      </div>
    </div>
  );
}
