import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Banner from "../components/banner/banner";
import NavBar from "../components/nav/navbar";
import SectionCards from "../components/card/section-cards";

import { getPopularVideos, getVideos } from "../lib/videos";

import magic from "../lib/magic-client";

export async function getServerSideProps() {
  const disneyVideos = await getVideos("disney trailer");
  const ProductivityVideos = await getVideos("Shade Zahrai");
  const TravelVideos = await getVideos("World Tour");

  const PopularVideos = await getPopularVideos();

  return {
    props: { disneyVideos, ProductivityVideos, TravelVideos, PopularVideos },
  };
}

export default function Home({
  disneyVideos,
  ProductivityVideos,
  TravelVideos,
  PopularVideos,
}) {
  console.log("Magic setup", magic);
  return (
    <div className={styles.container}>
      <Head>
        <title>NextFlix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <NavBar username="Ovesh@ov.com" />
        <Banner
          title="Clifford the red dog"
          subTitle="a very cute dog"
          imgUrl="/static/clifford.webp"
        />
        <div className={styles.sectionWrapper}>
          <SectionCards title={"Disney"} videos={disneyVideos} size="large" />
          <SectionCards title={"Travel"} videos={TravelVideos} size="small" />
          <SectionCards
            title={"Productivity"}
            videos={ProductivityVideos}
            size="medium"
          />
          <SectionCards title={"Popular"} videos={PopularVideos} size="small" />
        </div>
      </div>
    </div>
  );
}
